export { detectQCLI } from './q-cli-detector.js'
export { spawnQ } from './spawn-q.js'
export type { SpawnQOptions, SpawnQResult } from './spawn-q.js'
export { StreamProcessor } from './stream-processor.js'
export type { StreamProcessorConfig } from './stream-processor.js'
