name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Install dependencies
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build -o qube ./cmd/qube

      - name: Test
        run: go test -v -short ./...
